<?php
    $_productCollection=$this->getProductCollection();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
	$thumbnailWidth = $this->getThumbnailWidth();
	$thumbnailHeight = $this->getThumbnailHeight();
    
    require_once( Mage::getBaseDir('base') . '/app/code/local/NPS/BetterLayerNavigation/Helper/product.drop.class.php');
    $nps_prdctrl = new productDrop;
?>
<h2><?php echo $this->__('Best Sellers Products');?></h2>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="flexslider carousel" id="slideshow_bestseller">
	<?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php

        /**
        GET THE URL FOR LINKING TO THE CORRECT PAGE
        */
        //set the url for products to compensate for those with parents
        if( $nps_prdctrl->getChildOptionTypeID( $_product->getId() ) ){
            $nps_args = array(
                'npsf'=> $nps_prdctrl->getChildOptionTypeID( $_product->getId() )[0]['option_type_id'],
                );
            $_parentprdURL = $nps_prdctrl->getContainerProductURL( $_product->getId(), $nps_args );
        } else {
            $_parentprdURL = $_product->getProductUrl();
        }

        /**
        SEO MANU AND PRODUCT ID INSERT
        */
        //NPS SEO Title Configuration
        $manual_product_title = $_helper->productAttribute($_product, $_product->getName(), 'name');
        if( empty( $manual_product_title ) ){

            //set base title as manu - sku
            $nps_product_title = $_product->getAttributeText('manufacturer') . ' ' . $_product->getSku();

            //check if there is a short description
            $nps_short_desc = $_product->getShortDescription();
            if( !empty( $nps_short_desc ) ){

                //check if manufacturer name is included
                $nps_append = '';
                if( !strpos($nps_short_desc, $_product->getAttributeText('manufacturer') ) ){
                    $nps_append = $_product->getAttributeText('manufacturer') . ' ';
                }

                //check if sku is included
                if( strpos($nps_short_desc, $_product->getSku() ) == 0){
                    $nps_append .= $_product->getSku();
                }

                //check if prepend manufacturer and sku if missing
                if( !empty( $nps_append ) ){
                    $nps_product_title = $nps_append . ' - ' . $nps_short_desc;
                }
                
            } else {
                $nps_product_title = $_product->getAttributeText('manufacturer') . ' ' . $_product->getSku();
            }

        } else {
            $nps_product_title = $manual_product_title;

            //check if manufacturer name is included
            $nps_append = '';
            if( !strpos($nps_product_title, $_product->getAttributeText('manufacturer') ) ){
                $nps_append = $_product->getAttributeText('manufacturer') . ' ';
            }

            //check if sku is included
            if( strpos($nps_product_title, $_product->getSku() ) == 0){
                $nps_append .= $_product->getSku();
            }

            //check if prepend manufacturer and sku if missing
            if( !empty( $nps_append ) ){
                $nps_product_title = $nps_append . ' - ' . $nps_product_title;
            }
        }
    ?>
		<?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid slides">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%4==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_parentprdURL ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($widthgrid, $heightgrid); ?>" width="<?php echo $widthgrid ?>" height="<?php echo $heightgrid ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_parentprdURL ?>" title="<?php echo $this->stripTags($nps_product_title, null, true) ?>"><?php echo $nps_product_title; ?></a></h2>
                <!--span class="sku"><?php //echo $_product->getSku() ?></span-->
				<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
	<?php endforeach ?>
	<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
<?php endif; ?>